version: '3.3'

services:

  web:
      image: webdevops/php-nginx:7.3
      volumes:
          - ./:/app
      working_dir: /app
      ports:
          - "80:80"
      environment:
          WEB_DOCUMENT_ROOT: /app/public
          WEB_DOCUMENT_INDEX: index.php
          PHP_DATE_TIMEZONE: "Europe/Paris"
          PHP_DISPLAY_ERRORS: 1
